server:
  port: 8000


spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:

          - id: customer
            uri: lb://CUSTOMER
            predicates:
              - Path=/customer/api

          - id: coupon
            uri: lb://COUPON
            predicates:
              - Path=/coupon/api

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
