server:
  port: 8000


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: customer
          predicates:
            - Path=/customer/**
          uri: lb://CUSTOMER
        - id: coupon
          predicates:
            - Path=/coupon/**
          uri: lb://COUPON

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
